### ISSUE TITLE
640x480 support

### ISSUE THREAD

**Issue by Skilowi** [maniekx86/stillalive-os#6]
Need a 640x480 support here!
![20240209_175347](https://github.com/maniekx86/stillalive-os/assets/76708049/49582163-2eea-4230-9990-3ae0dd1739da)
A try to run from floppy.img on 701CS

Ran it early on Compaq in 800x600 and was running flawlessy. Wonderful!

**Comment by maniekx86** [comment]
Hi! Adding support for 640x480 mode might be not easy because fitting everything on the screen becomes almost impossible. Actually during development, I thought about that but I realized that I could not fit everything, which led me to opt for the 16-color 800x600 VESA mode instead. Theoretically, it could be possible to implement 640x480, but I would have to use a custom smaller font (there are no smaller than 8x8 fonts which we would need for this in VGA ROM), which I would have to create/copy and implement into code, and well, it could be a little difficult for the existing code base.

Also it's interesting to see how this laptop handles the 800x600 mode.

**Comment by maniekx86** [comment]
Closing as there is not much that I can do. 640x480 probably gonna never be supported by this project.
